name: mlops-k3-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - scikit-learn
    - mlflow
    - dagshub
    - joblib # (Pastikan ini ada)
    - "pydantic<2.0" # (Pastikan ini ada)